# -*-encoding: UTF-8 -*-
TIPO_FILA_NORMAL = 'normal'
TIPO_FILA_PRIORITARIA = 'prioritaria'

PREFIXO_FILA_NORMAL = 'NR'
PREFIXO_FILA_PRIORITARIA = 'PR'

TAMANHO_MAXIMO_FILA = 300
TAMANHO_MINIMO_FILA = 0
